version: "3.8"

services:
  db:
    image: mysql
    container_name: ex_08_db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /my/own/datadir:/var/lib/mysql

  spring:
    container_name: ex_08_back
    build: ./back_employee/.
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ex_08?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  react:
    container_name: ex_08_front
    build: ./front_employee/.
    ports:
      - "7777:80"
    depends_on:
      - db
      - spring

volumes:
  local_mysql_data:
