### GET request to example server
GET http://localhost:8080/api/products/all

###

POST http://localhost:8080/api/products/
Content-Type: application/json

{
  "name": "testName",
  "priceCents": 1
}
